### ISSUE TITLE
Need better color combinations, really.

### ISSUE THREAD

**Issue by resqiar** [resqiar/dikenang#163]
There are only a few colors available in this project, I know this might sound stupid but I don't have enough sense of magic for coloring things. So I need your help to give more stunning visualization colors.
Without more colors, the future feature will look so ugly and flat. take a look:

**v0.10.0 search feature a2564a246ae7f2176c5a1533a0b2ddc2fcbb7124**
![0.10.0 features](https://i.imgur.com/yugtStp.png)

### **Colors used all across the components, this is defined in [globals.css](https://github.com/resqiar/dikenang/blob/staging/dikweb/styles/globals.css)**
```css
/* global variables */
:root {
	/* Background Colors */
	--background: #0b0e10;
	--background-dimmed-200: #27313d;
	--background-dimmed-300: #252c37;
	--background-dimmed-400: #252c37;
	--background-dimmed-500: #151920;

	/* Fonts */
	--font-family: Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
		Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
		sans-serif;

	/* White Color */
	--font-white: rgba(255, 255, 255);
	--font-white-900: rgba(255, 255, 255, 0.9);
	--font-white-800: rgba(255, 255, 255, 0.8);
	--font-white-700: rgba(255, 255, 255, 0.7);
	--font-white-600: rgba(255, 255, 255, 0.6);
	--font-white-500: rgba(255, 255, 255, 0.5);
	--font-white-400: rgba(255, 255, 255, 0.4);
	--font-white-300: rgba(255, 255, 255, 0.3);
	--font-white-200: rgba(255, 255, 255, 0.2);
	--font-white-100: rgba(255, 255, 255, 0.1);

	/* Black color */

	--font-black: rgba(0, 0, 0);
	--font-black-900: rgba(0, 0, 0, 0.9);
	--font-black-800: rgba(0, 0, 0, 0.8);
	--font-black-700: rgba(0, 0, 0, 0.7);
	--font-black-600: rgba(0, 0, 0, 0.6);
	--font-black-500: rgba(0, 0, 0, 0.5);
	--font-black-400: rgba(0, 0, 0, 0.4);
	--font-black-300: rgba(0, 0, 0, 0.3);
	--font-black-200: rgba(0, 0, 0, 0.2);
	--font-black-100: rgba(0, 0, 0, 0.1);

	/* Grey Color */
	--font-grey: grey;

	/* colors */
	--color-primary: #3f51b5;

	/* Others */
	--box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.3);
	--box-shadow-18: 0 4px 18px 0 rgba(0, 0, 0, 0.3);
	--border: 1px solid rgb(71, 35, 35);
}
``` 
You can replace the CSS variables or simply create a new one with a meaningful variable name **(don't delete any available variables, just replace the value or create a new one)**
For example: 
```css
:root {
      ...

       /* Variable for Header Background */
	--header-background: rgb(71, 35, 35);
}
```

If you think your edit is good enough, send a pull request, I will review and give feedback asap.
